version: 2

models:
  - name: emp_details
    columns:
      - name: empno
        tests:
          - unique
          - not_null

sources:
  - name: DevProject
    database: dbt_Database  
    schema: dbt_Schema  
    tables:
      - name: emp